activeEnv: testEnv
browser:
  browserName: chrome
  browserAttachScreenshot: false
  headlessMode: false
  browserTimeout: 6
environments:
  testEnv:
    envName: testEnv
    appUrl: https://www.filmweb.pl/
    title: Filmweb - filmy takie jak Ty!
  intEnv:
    envName: intEnv
    appUrl: https://www.selenium.dev/
    title: Selenium